/**
 * @file    mbedtls_config.h
 * @brief   Minimal mbedTLS configuration for FOTA X.509 + ECDSA-P256 verification.
 *
 * Only the modules required for FOTA firmware signature verification are enabled:
 *   - X.509 certificate parsing (DER format)
 *   - ECDSA-P256 signature verification (software)
 *   - SHA-256 hash (software)
 *   - ASN.1 / PEM / BigNum supporting modules
 *
 * Hardware acceleration (future scope):
 *   - SHA-256: STM32H5 HASH peripheral (MBEDTLS_SHA256_ALT) — requires HAL HASH driver
 *   - ECDSA:   STM32H5 PKA peripheral  (MBEDTLS_ECDSA_VERIFY_ALT) — requires HAL PKA driver
 *   HAL HASH and PKA drivers are not currently in the project (not generated by CubeMX).
 *   To enable hardware alt: add stm32h5xx_hal_hash.h/.c and stm32h5xx_hal_pka.h/.c,
 *   enable HAL_HASH_MODULE_ENABLED and HAL_PKA_MODULE_ENABLED in stm32h5xx_hal_conf.h,
 *   then define MBEDTLS_SHA256_ALT and MBEDTLS_ECDSA_VERIFY_ALT here.
 *
 * NOT included:
 *   - TLS/DTLS stack (MBEDTLS_SSL_*)
 *   - RSA (MBEDTLS_RSA_C)
 *   - Symmetric ciphers (MBEDTLS_AES_C, etc.)
 *   - Network I/O (MBEDTLS_NET_C)
 *
 * [mbedTLS docs: https://mbed-tls.readthedocs.io/en/latest/]
 */

#ifndef MBEDTLS_CONFIG_H
#define MBEDTLS_CONFIG_H

/* ==========================================================================
 * Platform memory allocator
 * Use standard malloc/free (ARM toolchain heap in Secure RAM).
 * mbedTLS needs dynamic allocation only for X.509 certificate parsing.
 * We use mbedtls_platform_set_calloc_free() at runtime to redirect.
 * NOTE: Do NOT define MBEDTLS_PLATFORM_CALLOC_MACRO here — it causes
 * implicit declaration errors. Use the runtime API instead.
 * ========================================================================== */
#define MBEDTLS_PLATFORM_C
#define MBEDTLS_PLATFORM_MEMORY

/* ==========================================================================
 * Hash — SHA-256 (software implementation)
 * ========================================================================== */
#define MBEDTLS_SHA256_C

/* ==========================================================================
 * Elliptic Curve — ECDSA-P256 (software implementation)
 * ========================================================================== */
#define MBEDTLS_ECP_C
#define MBEDTLS_ECDSA_C
#define MBEDTLS_ECP_DP_SECP256R1_ENABLED   /* P-256 (prime256v1) only */
#define MBEDTLS_BIGNUM_C

/* ==========================================================================
 * X.509 Certificate Parsing
 * ========================================================================== */
#define MBEDTLS_X509_USE_C
#define MBEDTLS_X509_CRT_PARSE_C
#define MBEDTLS_ASN1_PARSE_C
#define MBEDTLS_ASN1_WRITE_C
#define MBEDTLS_OID_C
#define MBEDTLS_PK_C
#define MBEDTLS_PK_PARSE_C

/* ==========================================================================
 * Supporting modules
 * ========================================================================== */
#define MBEDTLS_MD_C
#define MBEDTLS_BASE64_C
#define MBEDTLS_PEM_PARSE_C

/* ==========================================================================
 * NOTE: Do NOT manually include mbedtls/check_config.h.
 * mbedTLS 3.x includes it automatically via mbedtls/build_info.h.
 * Manual inclusion triggers a #warning and may cause spurious errors.
 * ========================================================================== */

#endif /* MBEDTLS_CONFIG_H */
