# File automatically-generated by STM32CubeMX - Do not modify
set(ST_MULTICONTEXT TRUST_ZONE CACHE STRING "Type of multi-context")
#-----------------------Build Secure Project-----------------------#
if((${BUILD_CONTEXT} MATCHES .*Secure.*) OR (NOT DEFINED BUILD_CONTEXT))
    message("   Build context: " Secure)
    ExternalProject_Add(stm32h563_S
        BINARY_DIR                  ${CMAKE_SOURCE_DIR}/Secure/build
        SOURCE_DIR                  ${PROJECT_SOURCE_DIR}/Secure
        PREFIX                      Secure
        CONFIGURE_HANDLED_BY_BUILD  true
        INSTALL_COMMAND             ""
        CMAKE_ARGS                  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        BUILD_ALWAYS                true
    )

	set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_CLEAN_FILES "${CMAKE_SOURCE_DIR}/Secure/build")
	set(ST_TRUST_ZONE_SECURE_PROJECT_BUILD_TARGET ${CMAKE_SOURCE_DIR}/Secure/build/stm32h563_S${CMAKE_EXECUTABLE_SUFFIX_CXX} CACHE FILEPATH "Path to secure project target")
endif()
#-----------------------Build NonSecure Project-----------------------#
if((${BUILD_CONTEXT} MATCHES .*NonSecure.*) OR (NOT DEFINED BUILD_CONTEXT))
    message("   Build context: " NonSecure)
    ExternalProject_Add(stm32h563_NS
        BINARY_DIR                  ${CMAKE_SOURCE_DIR}/NonSecure/build
        SOURCE_DIR                  ${PROJECT_SOURCE_DIR}/NonSecure
        PREFIX                      NonSecure
        CONFIGURE_HANDLED_BY_BUILD  true
        INSTALL_COMMAND             ""
        CMAKE_ARGS                  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        BUILD_ALWAYS                true
        DEPENDS                     stm32h563_S
    )

	set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_CLEAN_FILES "${CMAKE_SOURCE_DIR}/NonSecure/build")
	set(ST_TRUST_ZONE_NONSECURE_PROJECT_BUILD_TARGET ${CMAKE_SOURCE_DIR}/NonSecure/build/stm32h563_NS${CMAKE_EXECUTABLE_SUFFIX_CXX} CACHE FILEPATH "Path to nonsecure project target")
endif()

