#!/usr/bin/env python3
# Copyright (c) 2026
# All rights reserved.

"""
Generate app_version.h with current Unix timestamp as build number.

This script is called at CMake **build time** (not configure time) via an
add_custom_target(ALL ...) so the build number updates on every
cmake --build invocation.

Usage:
    python tools/gen_version.py \\
        --output <path/to/app_version.h> \\
        --major 1 --minor 0 --patch 0
"""

import argparse
import pathlib
import sys
import time


# =============================================================================
# Header template
# =============================================================================

_HEADER_TEMPLATE = """\
/**
 * @file app_version.h
 * @brief Application version information.
 *
 * AUTO-GENERATED by tools/gen_version.py at build time.
 * DO NOT EDIT MANUALLY — regenerated on every cmake --build call.
 *
 * @copyright Copyright (c) 2026
 */

#ifndef APP_VERSION_H
#define APP_VERSION_H

#include <stdint.h>

/** Application version major number */
#define APP_VERSION_MAJOR  {major}U

/** Application version minor number */
#define APP_VERSION_MINOR  {minor}U

/** Application version patch number */
#define APP_VERSION_PATCH  {patch}U

/**
 * Application build number.
 *
 * Unix timestamp (seconds since epoch) captured at build time.
 * Stored as uint32_t — occupies 2 consecutive Modbus registers (big-endian).
 * Monotonically increasing and human-readable when converted to a date.
 */
#define APP_BUILD_NUMBER   {build_number}UL

#endif /* APP_VERSION_H */
"""


# =============================================================================
# Main
# =============================================================================


def _parse_args() -> argparse.Namespace:
    """Parse and return command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Generate app_version.h with current Unix timestamp as build number."
    )
    parser.add_argument(
        "--output",
        required=True,
        metavar="PATH",
        help="Output path for the generated app_version.h file.",
    )
    parser.add_argument(
        "--major",
        default="1",
        metavar="N",
        help="Application version major number (default: 1).",
    )
    parser.add_argument(
        "--minor",
        default="0",
        metavar="N",
        help="Application version minor number (default: 0).",
    )
    parser.add_argument(
        "--patch",
        default="0",
        metavar="N",
        help="Application version patch number (default: 0).",
    )
    return parser.parse_args()


def main() -> int:
    """Generate app_version.h and write it to the specified output path."""
    args = _parse_args()

    build_number = int(time.time())
    out_path = pathlib.Path(args.output)

    # Ensure the output directory exists
    out_path.parent.mkdir(parents=True, exist_ok=True)

    content = _HEADER_TEMPLATE.format(
        major=args.major,
        minor=args.minor,
        patch=args.patch,
        build_number=build_number,
    )

    out_path.write_text(content, encoding="utf-8")

    print(
        f"[gen_version.py] Generated {out_path} "
        f"(version={args.major}.{args.minor}.{args.patch}, build={build_number})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
